### ISSUE TITLE
Enable changing the default HSQLDB port from 9001 to another value

### ISSUE THREAD

**Issue by basdijkstra** [parasoft/parabank#23]
When I build ParaBank locally on my Windows 10 system and try to start the application, it generates an `Address already in use: JVM_Bind` error, because the default HSQLDB port of 9001 is already in use on my system. I could not find a reference to this port number, or a setting that allowed me to overwrite the default port, anywhere in the project.

After some investigation I found out that the `Intel(R) Graphics Command Center Service` was the culprit. This service, providing a GUI for changing Intel graphics settings on Windows 10 (and potentially other Windows versions, too), also uses port 9001.

After I disabled the service (I'm not using that GUI anyway), ParaBank started fine. This is an acceptable workaround for me, but I can imagine that it's not the same for other Windows 10 users with an Intel graphics unit. Or that they are even allowed to disable the service.

It would therefore be nice to have the option of specifying a non-default port number for the ParaBank database, as well as having updated docs that help others who run into the same issue. Happy to submit a PR if I only knew how to configure this..

**Comment by benken-parasoft** [comment]
In case anyone is wondering, here are some steps to manually change the HSQLDB port number from the default (9001) to some custom port number (9002).  I do this fairly often as I'll stand up multiple ParaBanks side-by-side in the same servlet container at different context paths.  You edit three files.  The files are located under src/main/resources.  In a deployed WAR they are found under "WEB-INF/classes".

**applicationContext-hsqldb.xml:** The port HSQLDB listens on.  Look for the "hsqldb" bean and its "props".  Add the following "prop", giving it the desired port number:
`<prop key="server.port">9002</prop>`

**jdbc.properties:** Change "jdbc.url" to include the desired port number:
`jdbc.url=jdbc:hsqldb:hsql://localhost:9002/parabank`

**jdbcBookstore.properties:**  Change the following properties to include the desired port number:
`jdbc.bookstoreURL=jdbc:hsqldb:hsql://localhost:9002/bookstore`
`jdbc.bookstorePort=9002`

**Comment by basdijkstra** [comment]
Thanks for that! I've just tested it and it works like a charm. I think it would be a good idea to add these to the installation docs, so others will not experience the same troubles. I'm using ParaBank extensively in my training offerings, and I would love to make the process of installing the application on people's local machines as smooth as possible.

Happy to submit a PR for that, if you don't take them, @benken-parasoft, I'll just close the issue and refer people to this issue instead.

**Comment by benken-parasoft** [comment]
I updated the README.md.

**Comment by basdijkstra** [comment]
Thanks!
