### ISSUE TITLE
Inconsistencies in the API specification

### ISSUE THREAD

**Issue by apicarve** [parasoft/parabank#32]
Hello, we are building a research tool to generate API test suites and API specification automatically using UI test suites. When we compared the API specification we generate with the specification provided along with the web application, we found a few inconsistencies. Would you consider this to be a problem with the API specification or with the application?

Here are the API endpoints for which the server provided a 2xx or a 3xx status but the specification does not include them.

```                    "/customers/{id}/accounts-options",
			"/customers/{id}/accounts-head",
			"/customers/{id}-options",
			"/customers/{id}-head",
			"/accounts/{id}/transactions/fromDate/04-20-2022/toDate/05-31-2022-options",
			"/accounts/{id}/transactions/fromDate/04-20-2022/toDate/05-31-2022-head",
			"/accounts/{id}/transactions-options",
			"/accounts/{id}/transactions-head",
			"/accounts/{id}-options",
			"/accounts/{id}-head",
			"/parabank-3.0.0-SNAPSHOT/services_proxy/bank/accounts/13566/transactions/onDate/20.0-options",
			"/parabank-3.0.0-SNAPSHOT/services_proxy/bank/accounts/13566/transactions/onDate/20.0-head"
```
For example `/customers/{id}-options` means that we tried the HTTP request `OPTIONS `on the API endpoint `/customers/{id}` and received a status 200 from the server. But there is no corresponding operation defined in the specification.

**Comment by benken-parasoft** [comment]
The HEAD method does seem to return the expected HTTP response headers that you would see for an equivalent GET.

The OPTIONS method returns a response with an Allow header which indicates which HTTP methods are available, something like this:
```
 HTTP/1.1 200
 Allow: POST,GET,OPTIONS,HEAD
 Date: Fri, 18 Nov 2022 18:44:41 GMT
 Content-Length: 0
```

Both HEAD and OPTIONS seem to behave as expected and are not part of the API.    I don't believe it is necessary or desirable to explicitly define HEAD or OPTIONS in ParaBank's service definition (OpenApi document).

**Comment by benken-parasoft** [comment]
OPTIONS and HEAD are not part of the API.  Therefore, they do not belong in API docs.  These HTTP verbs also seem to behave as expected having ParaBank hosted in Tomcat.  Whether such verbs or allowed or available can also depend on how the war is deployed, what servlet container you are using.  A reverse proxy can also be used to block certain verbs like OPTIONS.

**Comment by apicarve** [comment]
Thank you for the explanation.
